import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.scss'
import { useState, useEffect } from 'react'
import { MyAvatar } from '@/components/my-avatar/my-avatar';
import { CoolText } from '@/components/cool-text/cool-text';


export default function Home() {
  const [repositories, setRepositories] = useState<any[]>([]);
  const [error, setError] = useState<string | undefined>(undefined);

  // useEffect(() => {
  //   const fetchRepositories = async () => {
  //     try {
  //       const response = await fetch('/api/github/repositories');
  //       if (!response.ok) {
  //         throw new Error(`API responded with status: ${response.status}`);
  //       }
  //       const data: any = await response.json();
  //       setRepositories(data);
  //     } catch (error) {
  //       setError(error as string | undefined);
  //     }
  //   };

  //   fetchRepositories();
  // }, []);

  if (error) {
    return <div>Error: {error}</div>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', paddingTop: 24, flexDirection: 'column' }}>
          <MyAvatar />
          <div style={{ paddingTop: 24 }}>
            <CoolText text='Lyle' inline caption='Apparently means "island" or "from the island"' /> &nbsp;
            <CoolText text='February' inline caption='The second month of the year, in the northern hemisphere usually considered the last month of winter.' />
          </div>
        </div>

        <ul>
          {repositories.map(repo => (
            <li key={repo.id}>
              <a href={repo.html_url} target="_blank" rel="noopener noreferrer">
                {repo.name}
              </a> - {repo.description}
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}
