import Head from 'next/head'
import { useState } from 'react'
import projects from '@/data/projects.data';
import workExperiences from '@/data/workExperiences.data';
import { AvatarSection, ProjectsSection, WorkExperienceSection } from '@/components/home';
import Container from '@mui/material/Container';
import styles from '@/styles/Home.module.scss';

export default function Home() {
  const [repositories, setRepositories] = useState<any[]>([]);
  const [error, setError] = useState<string | undefined>(undefined);

  if (error) {
    return <div>Error: {error}</div>;
  }

  console.log(styles);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.stars}>
        {[...Array(32)].map((x, i) =>
          <div key={i} className={styles.star}></div>
        )}
      </div>
      <main className={styles.styledBackground}>
        <Container maxWidth="lg">
          <AvatarSection />
          <WorkExperienceSection workExperiences={workExperiences} />
          <ProjectsSection projects={projects} />
        </Container>

        <ul>
          {repositories.map(repo => (
            <li key={repo.id}>
              <a href={repo.html_url} target="_blank" rel="noopener noreferrer">
                {repo.name}
              </a> - {repo.description}
            </li>
          ))}
        </ul>
      </main>
    </>
  )
}
